"""add llm call traces table

Revision ID: 0e62e0d33e55
Revises: 62456308964b
Create Date: 2026-05-21 22:40:57.421550
"""
from alembic import op
import sqlalchemy as sa


revision = '0e62e0d33e55'
down_revision = '62456308964b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prompt_raw', sa.Text(), nullable=True),
    sa.Column('response_raw', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_call_traces_agent_name'), 'llm_call_traces', ['agent_name'], unique=False)
    op.create_index(op.f('ix_llm_call_traces_created_at'), 'llm_call_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_call_traces_model_name'), 'llm_call_traces', ['model_name'], unique=False)
    op.create_index(op.f('ix_llm_call_traces_status'), 'llm_call_traces', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_call_traces_status'), table_name='llm_call_traces')
    op.drop_index(op.f('ix_llm_call_traces_model_name'), table_name='llm_call_traces')
    op.drop_index(op.f('ix_llm_call_traces_created_at'), table_name='llm_call_traces')
    op.drop_index(op.f('ix_llm_call_traces_agent_name'), table_name='llm_call_traces')
    op.drop_table('llm_call_traces')
    # ### end Alembic commands ###
