"""add historical agent cache

Revision ID: 3e7a45f0cd22
Revises: e605f8609a75
Create Date: 2026-05-22 12:59:37.934473
"""
from alembic import op
import sqlalchemy as sa


revision = '3e7a45f0cd22'
down_revision = 'e605f8609a75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_agent_caches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_agent_caches_agent_name'), 'historical_agent_caches', ['agent_name'], unique=False)
    op.create_index(op.f('ix_historical_agent_caches_event_type'), 'historical_agent_caches', ['event_type'], unique=False)
    op.create_index(op.f('ix_historical_agent_caches_timestamp'), 'historical_agent_caches', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_agent_caches_timestamp'), table_name='historical_agent_caches')
    op.drop_index(op.f('ix_historical_agent_caches_event_type'), table_name='historical_agent_caches')
    op.drop_index(op.f('ix_historical_agent_caches_agent_name'), table_name='historical_agent_caches')
    op.drop_table('historical_agent_caches')
    # ### end Alembic commands ###
