"""refactor_signals_table

Revision ID: 62456308964b
Revises: 8304795c619f
Create Date: 2026-05-21 21:25:33.658308
"""

from alembic import op
import sqlalchemy as sa


revision = "62456308964b"
down_revision = "8304795c619f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("signals", sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("signals", sa.Column("price_snapshot_id", sa.Integer(), nullable=False))
    op.add_column("signals", sa.Column("indicator_id", sa.Integer(), nullable=True))
    op.add_column("signals", sa.Column("action", sa.String(length=16), nullable=False))
    op.add_column("signals", sa.Column("reason_code", sa.String(length=64), nullable=False))
    op.add_column("signals", sa.Column("price_usd_oz", sa.Numeric(precision=18, scale=6), nullable=False))
    op.add_column("signals", sa.Column("details_json", sa.JSON(), nullable=False))
    op.drop_index(op.f("ix_signals_asset_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_signal"), table_name="signals")
    op.drop_index(op.f("ix_signals_source"), table_name="signals")
    op.create_index(op.f("ix_signals_action"), "signals", ["action"], unique=False)
    op.create_index(op.f("ix_signals_indicator_id"), "signals", ["indicator_id"], unique=False)
    op.create_index(op.f("ix_signals_observed_at"), "signals", ["observed_at"], unique=False)
    op.create_index(op.f("ix_signals_price_snapshot_id"), "signals", ["price_snapshot_id"], unique=False)
    op.drop_constraint(op.f("signals_risk_decision_id_fkey"), "signals", type_="foreignkey")
    op.drop_constraint(op.f("signals_asset_id_fkey"), "signals", type_="foreignkey")
    op.create_foreign_key(None, "signals", "price_snapshots", ["price_snapshot_id"], ["id"])
    op.create_foreign_key(None, "signals", "technical_indicators", ["indicator_id"], ["id"])
    op.drop_column("signals", "source")
    op.drop_column("signals", "asset_id")
    op.drop_column("signals", "signal")
    op.drop_column("signals", "confidence")
    op.drop_column("signals", "risk_decision_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("signals", sa.Column("risk_decision_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "signals", sa.Column("confidence", sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False)
    )
    op.add_column("signals", sa.Column("signal", sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column("signals", sa.Column("asset_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("signals", sa.Column("source", sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, "signals", type_="foreignkey")
    op.drop_constraint(None, "signals", type_="foreignkey")
    op.create_foreign_key(op.f("signals_asset_id_fkey"), "signals", "assets", ["asset_id"], ["id"])
    op.create_foreign_key(
        op.f("signals_risk_decision_id_fkey"), "signals", "risk_decisions", ["risk_decision_id"], ["id"]
    )
    op.drop_index(op.f("ix_signals_price_snapshot_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_observed_at"), table_name="signals")
    op.drop_index(op.f("ix_signals_indicator_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_action"), table_name="signals")
    op.create_index(op.f("ix_signals_source"), "signals", ["source"], unique=False)
    op.create_index(op.f("ix_signals_signal"), "signals", ["signal"], unique=False)
    op.create_index(op.f("ix_signals_asset_id"), "signals", ["asset_id"], unique=False)
    op.drop_column("signals", "details_json")
    op.drop_column("signals", "price_usd_oz")
    op.drop_column("signals", "reason_code")
    op.drop_column("signals", "action")
    op.drop_column("signals", "indicator_id")
    op.drop_column("signals", "price_snapshot_id")
    op.drop_column("signals", "observed_at")
    # ### end Alembic commands ###
