"""add_resolved_source_and_is_degraded

Revision ID: 8304795c619f
Revises: 0004_add_tech_indicators
Create Date: 2026-05-21 16:16:48.289210
"""
from alembic import op
import sqlalchemy as sa


revision = '8304795c619f'
down_revision = '0004_add_tech_indicators'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assets_symbol_key'), 'assets', type_='unique')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.add_column('price_snapshots', sa.Column('resolved_source', sa.String(length=128), nullable=True))
    op.add_column('price_snapshots', sa.Column('is_degraded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('raw_bank_prices', sa.Column('resolved_source', sa.String(length=128), nullable=True))
    op.add_column('raw_bank_prices', sa.Column('is_degraded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint(op.f('risk_rules_code_key'), 'risk_rules', type_='unique')
    op.drop_index(op.f('ix_risk_rules_code'), table_name='risk_rules')
    op.create_index(op.f('ix_risk_rules_code'), 'risk_rules', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_rules_code'), table_name='risk_rules')
    op.create_index(op.f('ix_risk_rules_code'), 'risk_rules', ['code'], unique=False)
    op.create_unique_constraint(op.f('risk_rules_code_key'), 'risk_rules', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('raw_bank_prices', 'is_degraded')
    op.drop_column('raw_bank_prices', 'resolved_source')
    op.drop_column('price_snapshots', 'is_degraded')
    op.drop_column('price_snapshots', 'resolved_source')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_unique_constraint(op.f('assets_symbol_key'), 'assets', ['symbol'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
