"""add_agent_memory_events_table

Revision ID: e605f8609a75
Revises: 0e62e0d33e55
Create Date: 2026-05-21 22:45:45.983489
"""
from alembic import op
import sqlalchemy as sa


revision = 'e605f8609a75'
down_revision = '0e62e0d33e55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_events_agent_name'), 'agent_memory_events', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_memory_events_created_at'), 'agent_memory_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_memory_events_event_type'), 'agent_memory_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_memory_events_key'), 'agent_memory_events', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_memory_events_key'), table_name='agent_memory_events')
    op.drop_index(op.f('ix_agent_memory_events_event_type'), table_name='agent_memory_events')
    op.drop_index(op.f('ix_agent_memory_events_created_at'), table_name='agent_memory_events')
    op.drop_index(op.f('ix_agent_memory_events_agent_name'), table_name='agent_memory_events')
    op.drop_table('agent_memory_events')
    # ### end Alembic commands ###
